### ISSUE TITLE
Could this be extended to include the libwebp encoder as well?

### ISSUE THREAD

**Issue by Nantris** [chase-moskal/webp-hero#20]
I understand this is outside the scope of this project, but is the strategy you used able to be extended to encoding png to webp in browser?

**Comment by chase-moskal** [comment]
yes, i'm open to this idea!

here are my thoughts

- **we should add encoder functionality to webp-hero**
  - we should change `libwebp/Dockerfile` and the google libwebp emscripten settings, such that we generate a disambiguated `dwebp.js` (decoder) and `cwebp.js` (encoder) instead of `webp.js`
- **we should disambiguate the current `webp-machine`**
  - split it into a `webp-decoder` and also a `webp-encoder`, which could be loaded separately
- **we should publish webp-hero to github pages as a webapp**
  - free and easy clientside drag-and-drop batch webp/jpg/png conversions for everybody :)
  - maybe for batch conversions we could even output a downloadable .zip -- all clientside
  - the app won't have any advertising -- but we'll have a link and a heart for each github collaborator

see also
- [**issue 19: breaking refactors**](https://github.com/chase-moskal/webp-hero/issues/19) coming soon
- [**the webp-hero roadmap**](https://github.com/chase-moskal/webp-hero/projects/2), scheduled encoder/webapp for later

all pull requests and collaboration is very welcome and much appreciated

**Comment by chase-moskal** [comment]
closing due to lack of priority

still keen on the feature, so if you're interested to work on this, please open a new issue and we can chat about it!
