### ISSUE TITLE
How to use webp-hero with Angular 7?

### ISSUE THREAD

**Issue by SvenBudak** [chase-moskal/webp-hero#23]
Hi! we tryed to use this awesome lib in our Angular 7 Project. We added it to polyfill.ts but it isnt working. It simply do nothing. When a webp is loading simply nothing happens.

**Comment by chase-moskal** [comment]
@SvenBudak — hello my friend, i hope we can resolve this for you

could you post some example HTML or JS of how you've included and used webp-hero into your project?

webp-hero needs to be installed in two steps:

1. include the webp-hero library onto your page or into your application
2. instantiate a WebpMachine and run the polyfillDocument method

for now while you are setting it up, you can leave the polyfills out of the equation, because those are intended to support IE11

hopefully with more information we could resolve this issue

cheers! :wave:

**Comment by danil-naidonov** [comment]
> Hi! we tryed to use this awesome lib in our Angular 7 Project. We added it to polyfill.ts but it isnt working. It simply do nothing. When a webp is loading simply nothing happens.

**Step1: Add to providers in app.module.ts**
```
import {WebpMachine} from "webp-hero"

@NgModule({
  declarations: [AppComponent],
  providers: [ WebpMachine ],
  imports: [
    BrowserModule,
  ],
  bootstrap: [AppComponent]
})
export class AppModule {}
```

**Step2: Add to contructor in app.component.ts**

```
import { Component, OnInit } from '@angular/core';
import {WebpMachine} from "webp-hero";

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
    constructor(private webp: WebpMachine ) {
         this.webp.polyfillDocument();
     } 
    ngOnInit() {}
   
}
```

> But if you url has some params, it's can't help you. Becose author need fix bug in [issue](https://github.com/chase-moskal/webp-hero/issues/22). 

Author need re-write RegExp in condition from `if (/\.webp$/i.test(src)) {}` to `if (/.*webp.*/i.test(src)) {}`
it will find matches in Array of URL that are contained .webp but not at the end of the line .webp

**Comment by SvenBudak** [comment]
Ouh wow! Thanks for this awesome support! i will show this my friend and test this tomorrow.
Is there any way to limit this function to Safari, Safari Mobile and IE11? Is there any kind of browser detection includet that i can set with something like a config?

**Comment by danil-naidonov** [comment]
> Ouh wow! Thanks for this awesome support! i will show this my friend and test this tomorrow.
> Is there any way to limit this function to Safari, Safari Mobile and IE11? Is there any kind of browser detection includet that i can set with something like a config?

**Step 1: Create Function in component**

  
```
private enableWebpOnUnSupportBrowsers(): void {
         if (/msie\s|trident\/|edge\//i.test(window.navigator.userAgent)) {
             this.webp.polyfillDocument();
         }
    }
```

**Step 2: Run it in component ngOnInit**

```
ngOnInit() {
        this.enableWebpOnUnSupportBrowsers();
    }
```

**Comment by SvenBudak** [comment]
Yeah it's sadly not working because the URL param thing..

**Comment by coderbase-it** [comment]
Hi , i just try to integrate it in my angular 7 app like it described above , i try with last with dev.23 , dev.21 
same issue in IE 11 and Edge too : 

Edge say : Can't resolve all parameters for WebpMachine: (?).
IE 11 say :  ';' unexpected 


Regards,

**Comment by chase-moskal** [comment]
@coderbase-it — hmm, i'm not sure what this could be

the webp hero demo itself is still working in ie11, so this must be something about the way webp hero is installed in your angular app

could you perhaps show us a more exact error, with line numbers in the stack trace, and also quote the code that is throwing the exception?

i suspect perhaps, it might work better if you ensure that the polyfills are loading before webp-hero is, i wonder since it sort of looks like this angular issue https://github.com/angular/angular/issues/13609 shows some kind of relation to polyfills

webp-hero comes with a polyfill that you can use for ie11: https://unpkg.com/webp-hero@0.0.0-dev.23/dist-cjs/polyfills.js

i hope we get to the bottom of this,

cheers friend!

:wave: Chase

**Comment by alexisbmills** [comment]
@coderbase-it `WebpMachine` needs to be provided with different syntax to what @Lobasya used - the following will work:
```
export function webpMachineFactory() {
  return new WebpMachine();
}
// ...
providers: [
  { provide: WebpMachine, useFactory: webpMachineFactory }
]
/// ...
```

**Comment by alexisbmills** [comment]
I've implemented a working proof-of-concept of webp-hero with Angular (currently 8, but would work with lower versions), using a couple of Directives.

Example: https://github.com/alexisbmills/angular-universal-state-transfer-demo/pull/4 

The main implementation is in the `WebpPolyfillModule` and usage of Directives are in `UserComponent`. I've had to extract a bit of the private logic of `webp-hero` to apply the polyfill, similar to `polyfillImage`, using Angular's `Renderer2`.

**Comment by chase-moskal** [comment]
housekeeping here; i don't really understand this issue, but it seems like it's more about using angular than webp-hero specifically

i think i'll close it -- if anybody's still affected by this issue, just let me know!

👋 chase

**Comment by alexisbmills** [comment]
I agree. In the evaluation of webp-hero for Angular I've developed a reusable library for Angular projects (using webp-hero) - https://github.com/turnstileweb/ngx-webp-polyfill

[ngx-webp-polyfill](https://github.com/turnstileweb/ngx-webp-polyfill) utilises webp-hero's decode (webp -> png) logic but leaves the DOM manipulation to Angular.

**Comment by chase-moskal** [comment]
@alexisbmills — fantastic work!

i've just created #29 to set my intention to add a note about ngx-web-polyfill in the webp-hero readme

cheers, thanks for contributing!

:wave: chase
