### ISSUE TITLE
Comparison with libwebpjs

### ISSUE THREAD

**Issue by niutech** [chase-moskal/webp-hero#3]
How does webp-hero compare with [libwebpjs](http://libwebpjs.hohenlimburg.org/v0.6.0/)?

**Comment by chase-moskal** [comment]
- **webp-hero was designed to replace libwebpjs.** for my use-case, libwebpjs turned out to be buggy and outdated (libwebp*js* wasn't using the latest libwebp by google), and because libwebpjs source code is kept private and restricted, i had to create webp-hero so i could ensure i was using the latest bug-free code straight from google
- **webp-hero is completely open source,** contributions are welcome
- **webp-hero as a project, is really a machine** which can consistently download and build google's libwebp source code into a friendly javascript module, using the combined powers of docker, node, and various npm tools
- **webp-hero provide users with a nice commonjs module wrapper** around the google's decoder functionality
- **webp-hero is easily usable via popular package managers** like npm and yarn
- **webp-hero contains a dockerfile,** which performs the complete emscripten build of google's libwebp library, so you can easily manipulate the emscripten details yourself (for example you could decide to provide the javascript webp module more virtual memory, or just simply upgrade the google libwebp version being used, etc, by manipulating the details in that dockerfile)
- **webp-hero is fertile ground for contributions** — in particular, the javascript polyfill mechanism was sketched out quickly, and doesn't now hunt down every CSS image, though this enhancement would be rather trivial and very welcome — also, though it is also trivial, the version of libwebp should be updated in the dockerfile from time to time, it's been awhile now
- **webp-hero's docker build** could itself become an interesting feature, web-hero can be easily modified to also provide a ready docker container which you can use on your native machine to batch decode/encode large numbers of images locally

all in all, i'm hoping that developers will see that webp-hero is an open source alternative to libwebpjs which is better suited to accept contributions and collaboration, remain more up-to-date (in terms of tracking google's updates), and eventually become more feature-rich

**Comment by niutech** [comment]
Thank you for a thorough explanation. However, from end user
perspective, how do they compare in terms of performance and size?

**Comment by chase-moskal** [comment]
i haven't run any benchmarks

it would be very beneficial to workerize the decoder, that has not yet been done

**Comment by eMPee584** [comment]
Thanks a lot for creating this @chase-moskal! .. everything that libwepjs promised, + open source :heart_eyes: 
I think this should move to the wiki section..

**Comment by Nantris** [comment]
@chase-moskal, thanks so much for the thorough explanation. This project is amazing. Safari's lack of support for webp is inexplicable.

**Comment by prologic** [comment]
I haven't been able to get this to work in IE11 👎  I get no obvious errors in the console, I'm loading up the polyfills and the bundle and calling all the right stuff but images remain well unrendered.

**Comment by niutech** [comment]
@prologic The demo works fine in IE11:

![IE11](https://user-images.githubusercontent.com/384997/91124588-ce16a300-e69f-11ea-88b0-a5b7d051a96f.png)

**Comment by prologic** [comment]
Yeah I couldn't make it work I'm afraid in my test IE11 VM. Do you have to also have Flash installed?

In any case I opted for content negotiation instead of client-side JS re-encoding.

**Comment by niutech** [comment]
I have Flash, but it is irrelevant, because it is not used by WebP Hero. What are the exact errors in the console?

**Comment by prologic** [comment]
That's just the thing there were no errors, just no WebP images rendered at all.

**Comment by chase-moskal** [comment]
@prologic — i've just published a new version of webp-hero, and successfully tested it on IE11 under windows 7 — it seems to work — please try the latest version of webp-hero and let us know if you still experience your issue

also, do take a look at the new section near the top of the readme, about known issues and deficiencies — you might be experiencing one of those issues in your case

@niutech — thanks for the assitance posting the screenshot, very helpful!

:wave:

**Comment by prologic** [comment]
Will do! Thanks!
