### ISSUE TITLE
Working with webpack

### ISSUE THREAD

**Issue by JulianRojasBet** [chase-moskal/webp-hero#45]
This is not a library error but I hope you could help me. I was adding the webp-hero dependency to my project and using it as shown in the README, but I am having some problems building my app. I am getting the following error on build time:

```
Module parse failed: Unexpected token (29:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| export class WebpMachine {
>     webp;
|     webpSupport;
|     detectWebpImage;

 @ ./node_modules/webp-hero/dist/index.js 9:0-31 9:0-31
 @ ./src/polyfill/webp.js
 @ ./src/polyfill/index.js
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.1.12:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

I am not very proficient with Webpack so actually I do not know how can I fix it

Thanks for your work with this project, it is very helpful

**Comment by chase-moskal** [comment]
@JulianRojasBet hello, hopefully we can get this working for you soon

from the error you showed, it looks like you're trying to use the `es module` distribution of webp-hero — whereas you likely are in a situation where you need to load the `common js` distribution instead. please try directly importing the common js code this way:

```js
import {WebpMachine} from "webp-hero/dist-cjs/index.js"
```

let me know if this works for you, otherwise, you can reach out to me [on discord here at this link](https://discord.gg/YU2VKCyk) anytime so we can collaborate on this in realtime

🍻

**Comment by JulianRojasBet** [comment]
Awesome! Now works perfect, thanks for your help!
